apiVersion: v1
kind: Pod
metadata:
        name: jenkins
        labels:
                app: jenkins
spec:
        serviceAccountName: jenkins-service-account
        securityContext:
                fsGroup: 1000
        containers:
                - name: jenkins
                  securityContext:
                          runAsUser: 1000
                  image: bendonaldson2217/jenkins
                  ports:
                         - containerPort: 8080
                  volumeMounts:
                         - mountPath: "/var/jenkins_home"
                           name: jenkins-home
                         - mountPath: "/var/run/docker.sock"
                           name: docker-sock
        volumes:
                  - name: jenkins-home
                    persistentVolumeClaim:
                         claimName: jenkins-home
                  - name: docker-sock
                    hostPath:
                            path: /var/run/docker.sock
                            type: File
