apiVersion: apps/v1
kind: Deployment
metadata:
        name: email-service
        labels:
                app: email-service
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: email-service
        template:
                metadata:
                        labels:
                                app: email-service
                spec:
                        containers:
                                - name: email-service
                                  image: bendonaldson2217/email-service:latest
                                  ports:
                                          - containerPort: 3000
                                  env:
                                          - name: GMAIL_USER
                                            value: "ilovedocker123@gmail.com"
                                          - name: GMAIL_PASS
                                            value: "ilovedocker1!"
                                          - name: SERVICE_NAME
                                            value: "Example Project"

---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: session-token-service
        labels:
                app: session-token-service
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: session-token-service
        template:
                metadata:
                        labels:
                                app: session-token-service
                spec:
                        containers:
                                - name: session-token-service
                                  image: bendonaldson2217/session-token-service
                                  ports:
                                          - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: account-service
        labels:
                app: account-service
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: account-service
        template:
                metadata:
                        labels:
                                app: account-service
                spec:
                        containers:
                                - name: account-service
                                  image: bendonaldson2217/account-service:latest
                                  ports:
                                          - containerPort: 3000
