apiVersion: apps/v1
kind: Deployment
metadata:
        name: aes-encryption-service
        labels:
                app: aes-encription-service
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: aes-encryption-service
        template:
                metadata:
                        labels:
                                app: aes-encryption-service
                spec:
                        containers:
                                - name: aes-encryption-service
                                  image: bendonaldson2217/aes-encryption-service
                                  ports:
                                          - containerPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: secret-service
        labels:
                app: secret-service
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: secret-service
        template:
                metadata:
                        labels:
                                app: secret-service
                spec:
                        containers:
                                - name: secret-service
                                  image: bendonaldson2217/secret-service
                                  ports:
                                          - containerPort: 3000
