apiVersion: v1
kind: Service
metadata:
        name: dashboard-client
spec:
        selector:
                app: dashboard-client
        ports:
                - protocol: TCP
                  port: 8080
        type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
        name: authentication-service
spec:
        selector:
                app: authentication-service
        ports:
                - protocol: TCP
                  port: 3000
        type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
        name: dashboard-service
spec:
        selector:
                app: dashboard-service
        ports:
                - protocol: TCP
                  port: 3000
        type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
        name: authentication-client
spec:
        selector:
                app: authentication-client
        ports:
                - protocol: TCP
                  port: 8080
        type: ClusterIP
