apiVersion: v1
kind: Service
metadata:
        name: email-service
spec:
        selector:
                app: email-service
        ports:
                - protocol: TCP
                  port: 3000
        type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
        name: session-token-service
spec:
        selector:
                app: session-token-service
        ports:
                - protocol: TCP
                  port: 3000
        type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
        name: account-service
spec:
        selector:
                app: account-service
        ports:
                - protocol: TCP
                  port: 3000
        type: ClusterIP
